import '../models/user.dart';
import '../models/recipe.dart';

class RecipeDataService {
  static List<User> get users => [
    User(name: "Chef Maria", avatar: "👩‍🍳", isVerified: true, followers: 15200),
    User(name: "Cook Tony", avatar: "👨‍🍳", isVerified: true, followers: 8900),
    User(name: "Baker Sarah", avatar: "👩‍🍳", isVerified: true, followers: 22100),
    User(name: "Chef Luis", avatar: "👨‍🍳", isVerified: true, followers: 31500),
    User(name: "Anna K.", avatar: "👩‍🍳", isVerified: true, followers: 7800),
    User(name: "Chef Ben", avatar: "👨‍🍳", isVerified: true, followers: 19200),
  ];

  static List<Recipe> get recipes {
    final userList = users;
    return [
      Recipe(
        id: "1",
        title: "Truffle Risotto with Wild Mushrooms",
        imageUrl: "assets/img/risotto.png",
        category: "Italian",
        cookingTime: "45 mins",
        difficulty: "Advanced",
        servings: 4,
        rating: 4.8,
        likes: 1234,
        uploadedBy: userList[0],
        uploadDate: DateTime.now().subtract(Duration(hours: 3)),
        ingredients: [
          "400g Arborio rice",
          "200g mixed wild mushrooms",
          "50g black truffle",
          "1L warm chicken stock",
          "150ml white wine",
          "100g Parmesan cheese",
          "2 shallots, finely chopped",
          "3 cloves garlic",
          "50g butter",
          "Fresh thyme",
        ],
        instructions: [
          "Heat the chicken stock in a separate pan and keep it warm.",
          "In a heavy-bottomed pan, sauté chopped shallots in butter until translucent.",
          "Add minced garlic and cook for another minute.",
          "Add Arborio rice and stir for 2 minutes until rice is well-coated.",
          "Pour in white wine and stir until absorbed.",
          "Add warm stock one ladle at a time, stirring constantly.",
          "In a separate pan, sauté wild mushrooms until golden brown.",
          "Continue adding stock and stirring for about 18-20 minutes.",
          "Fold in sautéed mushrooms and grated Parmesan.",
          "Finish with shaved black truffle and fresh thyme.",
        ],
      ),
      Recipe(
        id: "2",
        title: "Chocolate Lava Cake",
        imageUrl: "assets/img/lava_cake.png",
        category: "Desserts",
        cookingTime: "25 mins",
        difficulty: "Medium",
        servings: 6,
        rating: 4.9,
        likes: 2156,
        uploadedBy: userList[2],
        uploadDate: DateTime.now().subtract(Duration(hours: 8)),
        ingredients: [
          "200g dark chocolate (70%)",
          "200g unsalted butter",
          "4 large eggs",
          "4 egg yolks",
          "100g caster sugar",
          "60g plain flour",
          "Butter for ramekins",
          "Cocoa powder for dusting",
          "Vanilla ice cream to serve",
        ],
        instructions: [
          "Preheat oven to 200°C. Grease 6 ramekins with butter and dust with cocoa powder.",
          "Melt chocolate and butter together in a double boiler until smooth.",
          "In a separate bowl, whisk whole eggs, egg yolks, and sugar until pale.",
          "Gradually fold the melted chocolate mixture into the egg mixture.",
          "Sift in flour and fold gently until just combined.",
          "Divide mixture evenly between prepared ramekins.",
          "Bake for 12-14 minutes until edges are set but centers still jiggle.",
          "Let cool for 1 minute, then run a knife around edges.",
          "Turn out onto serving plates and serve immediately with vanilla ice cream.",
        ],
      ),
      Recipe(
        id: "3",
        title: "Korean BBQ Beef Bowls",
        imageUrl: "assets/img/kbbq.png",
        category: "Korean",
        cookingTime: "30 mins",
        difficulty: "Easy",
        servings: 4,
        rating: 4.7,
        likes: 987,
        uploadedBy: userList[1],
        uploadDate: DateTime.now().subtract(Duration(days: 1)),
        ingredients: [
          "500g thinly sliced ribeye",
          "3 tbsp soy sauce",
          "2 tbsp brown sugar",
          "2 tbsp sesame oil",
          "3 cloves garlic, minced",
          "1 tbsp grated ginger",
          "2 cups cooked white rice",
          "1 cucumber, julienned",
          "2 carrots, julienned",
          "Sesame seeds for garnish",
          "Green onions, sliced",
        ],
        instructions: [
          "Marinate sliced beef in soy sauce, brown sugar, sesame oil, garlic, and ginger for 15 minutes.",
          "Heat a large skillet or wok over high heat.",
          "Cook marinated beef in batches for 2-3 minutes until caramelized.",
          "Prepare fresh vegetables by julienning cucumber and carrots.",
          "Divide cooked rice among serving bowls.",
          "Top with cooked beef and fresh vegetables.",
          "Garnish with sesame seeds and sliced green onions.",
          "Serve immediately with extra soy sauce on the side.",
        ],
      ),
      Recipe(
        id: "4",
        title: "Mediterranean Quinoa Salad",
        imageUrl: "assets/img/salad.png",
        category: "Healthy",
        cookingTime: "20 mins",
        difficulty: "Easy",
        servings: 6,
        rating: 4.6,
        likes: 756,
        uploadedBy: userList[4],
        uploadDate: DateTime.now().subtract(Duration(days: 2)),
        ingredients: [
          "2 cups quinoa, cooked and cooled",
          "1 cup cherry tomatoes, halved",
          "1 cucumber, diced",
          "200g feta cheese, cubed",
          "100g Kalamata olives",
          "1/2 red onion, thinly sliced",
          "1/4 cup fresh parsley",
          "1/4 cup fresh mint",
          "3 tbsp olive oil",
          "2 tbsp lemon juice",
          "Salt and pepper to taste",
        ],
        instructions: [
          "Cook quinoa according to package instructions and let cool completely.",
          "Prepare all vegetables: halve tomatoes, dice cucumber, slice red onion.",
          "Crumble feta cheese into bite-sized pieces.",
          "In a large bowl, combine cooled quinoa with all vegetables.",
          "Add feta cheese, olives, parsley, and mint.",
          "Whisk together olive oil, lemon juice, salt, and pepper for dressing.",
          "Pour dressing over salad and toss gently to combine.",
          "Let marinate for 10 minutes before serving for best flavor.",
          "Serve chilled or at room temperature.",
        ],
      ),
      Recipe(
        id: "5",
        title: "Authentic Ramen Bowl",
        imageUrl: "assets/img/ramen.png",
        category: "Japanese",
        cookingTime: "2 hours",
        difficulty: "Advanced",
        servings: 4,
        rating: 4.9,
        likes: 1876,
        uploadedBy: userList[3],
        uploadDate: DateTime.now().subtract(Duration(days: 3)),
        ingredients: [
          "1kg pork bones",
          "500g pork belly",
          "4 portions fresh ramen noodles",
          "4 soft-boiled eggs",
          "200g bamboo shoots",
          "4 sheets nori seaweed",
          "4 green onions, sliced",
          "2 tbsp miso paste",
          "2 tbsp soy sauce",
          "1 tbsp sesame oil",
          "Garlic cloves",
          "Fresh ginger",
        ],
        instructions: [
          "Make tonkotsu broth: Boil pork bones for 12+ hours until creamy white.",
          "Prepare chashu pork belly by braising in soy sauce and mirin.",
          "Soft-boil eggs for exactly 6.5 minutes, then marinate in tare sauce.",
          "Prepare bamboo shoots by blanching and seasoning.",
          "Cook ramen noodles according to package directions until al dente.",
          "Prepare tare (seasoning sauce) with miso, soy sauce, and garlic.",
          "Heat serving bowls and add 2 tbsp tare to each bowl.",
          "Add hot broth to dissolve tare, then add cooked noodles.",
          "Top with sliced chashu, halved egg, bamboo shoots, and nori.",
          "Garnish with green onions and serve immediately.",
        ],
      ),
      Recipe(
        id: "6",
        title: "Classic Margherita Pizza",
        imageUrl: "assets/img/pizza.png",
        category: "Italian",
        cookingTime: "3 hours",
        difficulty: "Medium",
        servings: 4,
        rating: 4.8,
        likes: 1543,
        uploadedBy: userList[5],
        uploadDate: DateTime.now().subtract(Duration(days: 4)),
        ingredients: [
          "500g 00 flour",
          "325ml lukewarm water",
          "10g salt",
          "3g active dry yeast",
          "2 tbsp olive oil",
          "400g San Marzano tomatoes",
          "300g fresh mozzarella",
          "Fresh basil leaves",
          "Extra virgin olive oil",
          "Sea salt",
          "Black pepper",
        ],
        instructions: [
          "Dissolve yeast in lukewarm water and let bloom for 5 minutes.",
          "Mix flour and salt in a large bowl, make a well in center.",
          "Add yeast mixture and olive oil, mix until rough dough forms.",
          "Knead for 10 minutes until smooth and elastic.",
          "Place in oiled bowl, cover, and rise for 2 hours until doubled.",
          "Crush San Marzano tomatoes by hand and season with salt.",
          "Divide dough into 4 portions and shape into balls.",
          "Stretch each ball into 10-inch circles, leaving thicker edges.",
          "Top with tomato sauce, torn mozzarella, and basil leaves.",
          "Bake at maximum oven temperature (250°C+) for 8-12 minutes.",
          "Finish with extra virgin olive oil and serve immediately.",
        ],
      ),
    ];
  }

  static List<Recipe> getRecipesByCategory(String category) {
    if (category == 'All') {
      return recipes;
    }
    return recipes.where((recipe) => recipe.category == category).toList();
  }

  static List<String> get categories => [
    'All',
    'Italian',
    'Japanese',
    'Korean',
    'Healthy',
    'Desserts'
  ];
}